name: Manual SonarQube Analysis

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory  # Directory for build-wrapper output

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures better analysis by fetching full history

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nlohmann-json3-dev

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      - name: Run Build Wrapper with Compilation
        run: |
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} \
          g++ -I include src/*.cpp app/main.cpp -lssl -lcrypto -o fortressfs

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Uses secret for authentication
        with:
          args: >
            --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"
